// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackPivot.Control.Infrastructure.Persistence;

#nullable disable

namespace StackPivot.Control.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StackPivotDbContext))]
    [Migration("20260901195320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.AgentNode", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeyLast4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_last4");

                    b.Property<int>("ApiKeyVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_key_version");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<string>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.HasKey("AgentId");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("agent_node", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_ip");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.HasKey("AuditId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResourceId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.DeploymentRequestEntity", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_fingerprint");

                    b.Property<Guid>("StackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_id");

                    b.Property<string>("TargetCommitHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_commit_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("RequestId");

                    b.HasIndex("StackId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("deployment_request", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.GlobalGitSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token_encrypted");

                    b.Property<string>("GitRepo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("git_repo");

                    b.Property<string>("GitUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("git_user_name");

                    b.Property<string>("TokenKeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_key_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("global_git_setting", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.ServiceOperationHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("history_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_text");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<string>("FinishTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_time");

                    b.Property<string>("LastEventAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_event_at");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sequence");

                    b.Property<bool>("LogTruncated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_truncated");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<string>("OutputLog")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output_log");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<Guid>("StackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_id");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("TargetCommitHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_commit_hash");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.HasIndex("AgentId", "LastEventAt");

                    b.HasIndex("StackId", "LastEventAt");

                    b.ToTable("service_operation_history", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.Stack", b =>
                {
                    b.Property<Guid>("StackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("StackId");

                    b.HasIndex("WorkspaceId", "FolderName")
                        .IsUnique();

                    b.ToTable("stack", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.StackAgentBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("StackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("StackId", "AgentId")
                        .IsUnique();

                    b.ToTable("stack_agent_binding", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_platform_admin");

                    b.Property<string>("SsoSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("sso_subject");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("SsoSubject")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("workspace", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("workspace_member", (string)null);
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.DeploymentRequestEntity", b =>
                {
                    b.HasOne("StackPivot.Control.Domain.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.ServiceOperationHistory", b =>
                {
                    b.HasOne("StackPivot.Control.Domain.Entities.DeploymentRequestEntity", null)
                        .WithMany("Operations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackPivot.Control.Domain.Entities.Stack", "Stack")
                        .WithMany("Operations")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.Stack", b =>
                {
                    b.HasOne("StackPivot.Control.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Stacks")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.StackAgentBinding", b =>
                {
                    b.HasOne("StackPivot.Control.Domain.Entities.AgentNode", "Agent")
                        .WithMany("StackBindings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackPivot.Control.Domain.Entities.Stack", "Stack")
                        .WithMany("AgentBindings")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("StackPivot.Control.Domain.Entities.UserAccount", "User")
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackPivot.Control.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.AgentNode", b =>
                {
                    b.Navigation("StackBindings");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.DeploymentRequestEntity", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.Stack", b =>
                {
                    b.Navigation("AgentBindings");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("WorkspaceMembers");
                });

            modelBuilder.Entity("StackPivot.Control.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Stacks");
                });
#pragma warning restore 612, 618
        }
    }
}
